### ISSUE TITLE
test 1.8.7 compatibility

### ISSUE THREAD

**Issue by ricokareem** [attinteractive/yacht#16]
we gotta test yacht and cap deployment with yacht under ruby enterprise 1.8.7

**Comment by bowsersenior** [comment]
We can test that Yacht's compatibility with ruby 1.8.7 as part of this repo. Yacht should not have any effect on Capistrano's compatibility with ruby 1.8.7.

**Comment by bowsersenior** [comment]
Yacht is NOT compatible with ruby 1.8.7 . There are 2 issues:
1. BasicObject is not defined in 1.8.7 (easy to fix)
2. Rails specs don't work in 1.8.7 due to infinite loop when loading `yacht/rails` (harder to fix)

Will work on making Yacht fully compatible with ruby 1.8.7.
