### ISSUE TITLE
js_comment in yacht / lib / yacht / javascript.rb  needs to standout

### ISSUE THREAD

**Issue by fuentesjr** [attinteractive/yacht#5]
---

< DO NOT EDIT THIS FILE DIRECTLY >

---

```
    \   ^__^
     \  (oo)\_______
        (__)\       )\/\
            ||----w |
            ||     ||
```

**Comment by fuentesjr** [comment]
See: https://github.com/attinteractive/yacht/pull/9

**Comment by bowsersenior** [comment]
Holy sh*t! Closed by this awesome commit:
- https://github.com/attinteractive/yacht/commit/39f0b8298239886bef41413ce6f3d026388bf5c2
